# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('keywords', models.CharField(blank=True, max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('institution', models.CharField(max_length=128)),
                ('content', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
    ]
